### ISSUE TITLE
Diagnostic provider "outsourced" errored

### ISSUE THREAD

**Issue by daniel-horizon** [phpactor/vscode-phpactor#113]
I get this error when VSCode loads, can this be fixed?

`[2024-03-08 13:52:31] phpactor.ERROR: Diagnostic provider "outsourced" errored with "Failed to write to stream; fwrite(): Write of 619 bytes failed with errno=32 Broken pipe", removing from pool {"channel":"LSPDIAG","stack":"#0 [internal function]: Phpactor\\LanguageServer\\Core\\Diagnostics\\DiagnosticsEngine->Phpactor\\LanguageServer\\Core\\Diagnostics\\{closure}()\n#1 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Coroutine.php(115): Generator->throw(Object(Amp\\ByteStream\\StreamException))\n#2 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Failure.php(33): Amp\\Coroutine->Amp\\{closure}(Object(Amp\\ByteStream\\StreamException), NULL)\n#3 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Internal/Placeholder.php(143): Amp\\Failure->onResolve(Object(Closure))\n#4 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Internal/Placeholder.php(177): Amp\\Coroutine->resolve(Object(Amp\\Failure))\n#5 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Coroutine.php(137): Amp\\Coroutine->fail(Object(Amp\\ByteStream\\StreamException))\n#6 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Failure.php(33): Amp\\Coroutine->Amp\\{closure}(Object(Amp\\ByteStream\\StreamException), NULL)\n#7 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Internal/Placeholder.php(143): Amp\\Failure->onResolve(Object(Closure))\n#8 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Deferred.php(53): Amp\\Promise@anonymous->resolve(Object(Amp\\Failure))\n#9 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/process/lib/ProcessOutputStream.php(48): Amp\\Deferred->resolve(Object(Amp\\Failure))\n#10 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\\Process\\ProcessOutputStream->Amp\\Process\\{closure}(NULL, Object(Amp\\ByteStream\\ResourceOutputStream))\n#11 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Deferred.php(53): Amp\\Promise@anonymous->resolve(Object(Amp\\ByteStream\\ResourceOutputStream))\n#12 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/process/lib/Internal/Posix/Runner.php(71): Amp\\Deferred->resolve(Object(Amp\\ByteStream\\ResourceOutputStream))\n#13 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\\Process\\Internal\\Posix\\Runner::onProcessStartExtraDataPipeReadable('j', Resource id #5698, Array)\n#14 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Loop/NativeDriver.php(124): Amp\\Loop\\NativeDriver->selectStreams(Array, Array, 0)\n#15 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\\Loop\\NativeDriver->dispatch(false)\n#16 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\\Loop\\Driver->tick()\n#17 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/amphp/amp/lib/Loop.php(95): Amp\\Loop\\Driver->run()\n#18 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(111): Amp\\Loop::run(Object(Closure))\n#19 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/lib/Extension/LanguageServer/Command/StartCommand.php(50): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->run()\n#20 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/symfony/console/Command/Command.php(298): Phpactor\\Extension\\LanguageServer\\Command\\StartCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand(Object(Phpactor\\Extension\\LanguageServer\\Command\\StartCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#23 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/lib/Application.php(48): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#24 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/vendor/symfony/console/Application.php(171): Phpactor\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#25 phar:///home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar/bin/phpactor(45): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#26 /home/developer/.vscode-server/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar(15): require('phar:///home/de...')\n#27 {main}"} []
`

**Comment by dantleech** [comment]
What O/S are you running, how are you running Phpactor?

**Comment by daniel-horizon** [comment]
Hi, Thanks for your reply. I'm running inside a docker container from a php:8.2-fpm image.

My setup is devcontainers with VSCode. I'm installing and enabling pcntl and installing phpactor in the container.

```developer@aaab379e6ae4:/var/www/html$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"```

**Comment by dantleech** [comment]
I'm pretty sure others have had issues with this configuration cc @BladeMF ... you can try disabling "outsouved diagnostics" (check configuration reference) though I'm not sure how far you'll get after that.

**Comment by zobo** [comment]
Just want to say same happens to me and I'll investigate when I can.
![image](https://github.com/phpactor/vscode-phpactor/assets/2456026/5d70f90a-bdef-4af9-b9ab-ae824fd8d32c)

Don't see a cause at the moment...
