### ISSUE TITLE
Invalid type arguments for Position

### ISSUE THREAD

**Issue by piporoid** [phpactor/vscode-phpactor#27]
When using the vscode-phpactor together with standard PHP plugin , the following error may occur.

```
[[0;32mINFO[0;0m][[1;37m973742.766205[0;0m] IN:{
    "jsonrpc": "2.0",
    "id": 26,
    "method": "textDocument\/codeAction",
    "params": {
        "textDocument": {
            "uri": "file:\/\/\/home\/pipopa\/PHP\/test-php-project\/src\/Book.php"
        },
        "range": {
            "start": {
                "line": 8,
                "character": 4
            },
            "end": {
                "line": 8,
                "character": 1.7976931348623157e+308
            }
        },
        "context": {
            "diagnostics": [
                {
                    "range": {
                        "start": {
                            "line": 8,
                            "character": 0
                        },
                        "end": {
                            "line": 8,
                            "character": 1.7976931348623157e+308
                        }
                    },
                    "message": "syntax error, unexpected '\"', expecting '('",
                    "severity": 1
                }
            ],
            "only": [
                "quickfix"
            ]
        }
    }
}
[[0;32mINFO[0;0m][[1;37m973742.766403[0;0m] OUT: {
    "id": 26,
    "result": null,
    "error": {
        "code": -32603,
        "message": "Exception [DTL\\Invoke\\Exception\\InvalidParameterType] Argument \"character\" has type \"int\" but was passed \"double\" for \"Phpactor\\LanguageServerProtocol\\Position#__construct\"",
        "data": "#0 \/home\/pipopa\/Git\/phpactor\/vendor\/dantleech\/invoke\/src\/Invoke.php(120): DTL\\Invoke\\Internal\\ArgumentAssert::types()\n#1 \/home\/pipopa\/Git\/phpactor\/vendor\/dantleech\/invoke\/src\/Invoke.php(79): DTL\\Invoke\\Invoke->instantiate()\n#2 \/home\/pipopa\/Git\/phpactor\/vendor\/dantleech\/invoke\/src\/Invoke.php(43): DTL\\Invoke\\Invoke->doInstantiate()\n#3 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server-protocol\/src\/Position.php(104): DTL\\Invoke\\Invoke::new()\n#4 [internal function]: Phpactor\\LanguageServerProtocol\\Position::fromArray()\n#5 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server-protocol\/src\/Range.php(112): call_user_func_array()\n#6 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server-protocol\/src\/Range.php(96): Phpactor\\LanguageServerProtocol\\Range::invokeFromNames()\n#7 [internal function]: Phpactor\\LanguageServerProtocol\\Range::fromArray()\n#8 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server-protocol\/src\/CodeActionParams.php(135): call_user_func_array()\n#9 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server-protocol\/src\/CodeActionParams.php(119): Phpactor\\LanguageServerProtocol\\CodeActionParams::invokeFromNames()\n#10 [internal function]: Phpactor\\LanguageServerProtocol\\CodeActionParams::fromArray()\n#11 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Dispatcher\/ArgumentResolver\/LanguageSeverProtocolParamsResolver.php(68): ReflectionMethod->invoke()\n#12 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Dispatcher\/ArgumentResolver\/LanguageSeverProtocolParamsResolver.php(42): Phpactor\\LanguageServer\\Core\\Dispatcher\\ArgumentResolver\\LanguageSeverProtocolParamsResolver->doResolveArguments()\n#13 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Dispatcher\/ArgumentResolver\/ChainArgumentResolver.php(28): Phpactor\\LanguageServer\\Core\\Dispatcher\\ArgumentResolver\\LanguageSeverProtocolParamsResolver->resolveArguments()\n#14 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Handler\/HandlerMethodRunner.php(83): Phpactor\\LanguageServer\\Core\\Dispatcher\\ArgumentResolver\\ChainArgumentResolver->resolveArguments()\n#15 [internal function]: Phpactor\\LanguageServer\\Core\\Handler\\HandlerMethodRunner->Phpactor\\LanguageServer\\Core\\Handler\\{closure}()\n#16 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Coroutine.php(67): Generator->current()\n#17 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/functions.php(96): Amp\\Coroutine->__construct()\n#18 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Handler\/HandlerMethodRunner.php(102): Amp\\call()\n#19 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Middleware\/HandlerMiddleware.php(38): Phpactor\\LanguageServer\\Core\\Handler\\HandlerMethodRunner->dispatch()\n#20 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Middleware\/RequestHandler.php(37): Phpactor\\LanguageServer\\Middleware\\HandlerMiddleware->process()\n#21 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Middleware\/ResponseHandlingMiddleware.php(35): Phpactor\\LanguageServer\\Core\\Middleware\\RequestHandler->handle()\n#22 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Middleware\/RequestHandler.php(37): Phpactor\\LanguageServer\\Middleware\\ResponseHandlingMiddleware->process()\n#23 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Middleware\/MethodAliasMiddleware.php(37): Phpactor\\LanguageServer\\Core\\Middleware\\RequestHandler->handle()\n#24 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Middleware\/RequestHandler.php(37): Phpactor\\LanguageServer\\Middleware\\MethodAliasMiddleware->process()\n#25 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Middleware\/CancellationMiddleware.php(49): Phpactor\\LanguageServer\\Core\\Middleware\\RequestHandler->handle()\n#26 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Middleware\/RequestHandler.php(37): Phpactor\\LanguageServer\\Middleware\\CancellationMiddleware->process()\n#27 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Middleware\/InitializeMiddleware.php(68): Phpactor\\LanguageServer\\Core\\Middleware\\RequestHandler->handle()\n#28 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Middleware\/RequestHandler.php(37): Phpactor\\LanguageServer\\Middleware\\InitializeMiddleware->process()\n#29 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Middleware\/ErrorHandlingMiddleware.php(39): Phpactor\\LanguageServer\\Core\\Middleware\\RequestHandler->handle()\n#30 [internal function]: Phpactor\\LanguageServer\\Middleware\\ErrorHandlingMiddleware->Phpactor\\LanguageServer\\Middleware\\{closure}()\n#31 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Coroutine.php(67): Generator->current()\n#32 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/functions.php(96): Amp\\Coroutine->__construct()\n#33 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Middleware\/ErrorHandlingMiddleware.php(64): Amp\\call()\n#34 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Middleware\/RequestHandler.php(37): Phpactor\\LanguageServer\\Middleware\\ErrorHandlingMiddleware->process()\n#35 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Dispatcher\/Dispatcher\/MiddlewareDispatcher.php(29): Phpactor\\LanguageServer\\Core\\Middleware\\RequestHandler->handle()\n#36 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Server\/LanguageServer.php(223): Phpactor\\LanguageServer\\Core\\Dispatcher\\Dispatcher\\MiddlewareDispatcher->dispatch()\n#37 [internal function]: Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->Phpactor\\LanguageServer\\Core\\Server\\{closure}()\n#38 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Coroutine.php(67): Generator->current()\n#39 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/functions.php(96): Amp\\Coroutine->__construct()\n#40 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/functions.php(121): Amp\\call()\n#41 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Server\/LanguageServer.php(240): Amp\\asyncCall()\n#42 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Server\/LanguageServer.php(214): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->dispatchRequest()\n#43 [internal function]: Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->Phpactor\\LanguageServer\\Core\\Server\\{closure}()\n#44 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Coroutine.php(118): Generator->send()\n#45 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Internal\/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}()\n#46 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Coroutine.php(123): Amp\\Coroutine->resolve()\n#47 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Internal\/Placeholder.php(149): Amp\\Coroutine->Amp\\{closure}()\n#48 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Deferred.php(52): class@anonymous->resolve()\n#49 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/byte-stream\/lib\/ResourceInputStream.php(101): Amp\\Deferred->resolve()\n#50 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Loop\/NativeDriver.php(321): Amp\\ByteStream\\ResourceInputStream::Amp\\ByteStream\\{closure}()\n#51 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Loop\/NativeDriver.php(127): Amp\\Loop\\NativeDriver->selectStreams()\n#52 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Loop\/Driver.php(138): Amp\\Loop\\NativeDriver->dispatch()\n#53 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Loop\/Driver.php(72): Amp\\Loop\\Driver->tick()\n#54 \/home\/pipopa\/Git\/phpactor\/vendor\/amphp\/amp\/lib\/Loop.php(95): Amp\\Loop\\Driver->run()\n#55 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server\/lib\/Core\/Server\/LanguageServer.php(113): Amp\\Loop::run()\n#56 \/home\/pipopa\/Git\/phpactor\/vendor\/phpactor\/language-server-extension\/lib\/LanguageServer\/Command\/StartCommand.php(59): Phpactor\\LanguageServer\\Core\\Server\\LanguageServer->run()\n#57 \/home\/pipopa\/Git\/phpactor\/vendor\/symfony\/console\/Command\/Command.php(288): Phpactor\\Extension\\LanguageServer\\Command\\StartCommand->execute()\n#58 \/home\/pipopa\/Git\/phpactor\/vendor\/symfony\/console\/Application.php(974): Symfony\\Component\\Console\\Command\\Command->run()\n#59 \/home\/pipopa\/Git\/phpactor\/vendor\/symfony\/console\/Application.php(291): Symfony\\Component\\Console\\Application->doRunCommand()\n#60 \/home\/pipopa\/Git\/phpactor\/lib\/Application.php(54): Symfony\\Component\\Console\\Application->doRun()\n#61 \/home\/pipopa\/Git\/phpactor\/vendor\/symfony\/console\/Application.php(167): Phpactor\\Application->doRun()\n#62 \/home\/pipopa\/Git\/phpactor\/bin\/phpactor(42): Symfony\\Component\\Console\\Application->run()\n#63 {main}"
    },
    "jsonrpc": "2.0"
}
[Error - 10:35:42 PM] Request textDocument/codeAction failed.
  Message: Exception [DTL\Invoke\Exception\InvalidParameterType] Argument "character" has type "int" but was passed "double" for "Phpactor\LanguageServerProtocol\Position#__construct"
  Code: -32603 
#0 /home/pipopa/Git/phpactor/vendor/dantleech/invoke/src/Invoke.php(120): DTL\Invoke\Internal\ArgumentAssert::types()
#1 /home/pipopa/Git/phpactor/vendor/dantleech/invoke/src/Invoke.php(79): DTL\Invoke\Invoke->instantiate()
#2 /home/pipopa/Git/phpactor/vendor/dantleech/invoke/src/Invoke.php(43): DTL\Invoke\Invoke->doInstantiate()
#3 /home/pipopa/Git/phpactor/vendor/phpactor/language-server-protocol/src/Position.php(104): DTL\Invoke\Invoke::new()
#4 [internal function]: Phpactor\LanguageServerProtocol\Position::fromArray()
#5 /home/pipopa/Git/phpactor/vendor/phpactor/language-server-protocol/src/Range.php(112): call_user_func_array()
#6 /home/pipopa/Git/phpactor/vendor/phpactor/language-server-protocol/src/Range.php(96): Phpactor\LanguageServerProtocol\Range::invokeFromNames()
#7 [internal function]: Phpactor\LanguageServerProtocol\Range::fromArray()
#8 /home/pipopa/Git/phpactor/vendor/phpactor/language-server-protocol/src/CodeActionParams.php(135): call_user_func_array()
#9 /home/pipopa/Git/phpactor/vendor/phpactor/language-server-protocol/src/CodeActionParams.php(119): Phpactor\LanguageServerProtocol\CodeActionParams::invokeFromNames()
#10 [internal function]: Phpactor\LanguageServerProtocol\CodeActionParams::fromArray()
#11 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/ArgumentResolver/LanguageSeverProtocolParamsResolver.php(68): ReflectionMethod->invoke()
#12 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/ArgumentResolver/LanguageSeverProtocolParamsResolver.php(42): Phpactor\LanguageServer\Core\Dispatcher\ArgumentResolver\LanguageSeverProtocolParamsResolver->doResolveArguments()
#13 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/ArgumentResolver/ChainArgumentResolver.php(28): Phpactor\LanguageServer\Core\Dispatcher\ArgumentResolver\LanguageSeverProtocolParamsResolver->resolveArguments()
#14 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(83): Phpactor\LanguageServer\Core\Dispatcher\ArgumentResolver\ChainArgumentResolver->resolveArguments()
#15 [internal function]: Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->Phpactor\LanguageServer\Core\Handler\{closure}()
#16 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#17 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#18 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Handler/HandlerMethodRunner.php(102): Amp\call()
#19 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Middleware/HandlerMiddleware.php(38): Phpactor\LanguageServer\Core\Handler\HandlerMethodRunner->dispatch()
#20 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\HandlerMiddleware->process()
#21 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Middleware/ResponseHandlingMiddleware.php(35): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#22 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ResponseHandlingMiddleware->process()
#23 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Middleware/MethodAliasMiddleware.php(37): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#24 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\MethodAliasMiddleware->process()
#25 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Middleware/CancellationMiddleware.php(49): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#26 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\CancellationMiddleware->process()
#27 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Middleware/InitializeMiddleware.php(68): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#28 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\InitializeMiddleware->process()
#29 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(39): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#30 [internal function]: Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->Phpactor\LanguageServer\Middleware\{closure}()
#31 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#32 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#33 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Middleware/ErrorHandlingMiddleware.php(64): Amp\call()
#34 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Middleware/RequestHandler.php(37): Phpactor\LanguageServer\Middleware\ErrorHandlingMiddleware->process()
#35 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Dispatcher/Dispatcher/MiddlewareDispatcher.php(29): Phpactor\LanguageServer\Core\Middleware\RequestHandler->handle()
#36 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(223): Phpactor\LanguageServer\Core\Dispatcher\Dispatcher\MiddlewareDispatcher->dispatch()
#37 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#38 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#39 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#40 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/functions.php(121): Amp\call()
#41 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(240): Amp\asyncCall()
#42 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(214): Phpactor\LanguageServer\Core\Server\LanguageServer->dispatchRequest()
#43 [internal function]: Phpactor\LanguageServer\Core\Server\LanguageServer->Phpactor\LanguageServer\Core\Server\{closure}()
#44 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#45 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#46 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve()
#47 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#48 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve()
#49 /home/pipopa/Git/phpactor/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#50 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(321): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#51 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams()
#52 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#53 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#54 /home/pipopa/Git/phpactor/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#55 /home/pipopa/Git/phpactor/vendor/phpactor/language-server/lib/Core/Server/LanguageServer.php(113): Amp\Loop::run()
#56 /home/pipopa/Git/phpactor/vendor/phpactor/language-server-extension/lib/LanguageServer/Command/StartCommand.php(59): Phpactor\LanguageServer\Core\Server\LanguageServer->run()
#57 /home/pipopa/Git/phpactor/vendor/symfony/console/Command/Command.php(288): Phpactor\Extension\LanguageServer\Command\StartCommand->execute()
#58 /home/pipopa/Git/phpactor/vendor/symfony/console/Application.php(974): Symfony\Component\Console\Command\Command->run()
#59 /home/pipopa/Git/phpactor/vendor/symfony/console/Application.php(291): Symfony\Component\Console\Application->doRunCommand()
#60 /home/pipopa/Git/phpactor/lib/Application.php(54): Symfony\Component\Console\Application->doRun()
#61 /home/pipopa/Git/phpactor/vendor/symfony/console/Application.php(167): Phpactor\Application->doRun()
#62 /home/pipopa/Git/phpactor/bin/phpactor(42): Symfony\Component\Console\Application->run()
#63 {main}
```

This error is probably caused by the use of floating point numbers by standard PHP plugins.
https://github.com/microsoft/vscode/blob/main/extensions/php-language-features/src/features/validationProvider.ts#L200 

It seems that the next release of vscode-languageclient will have a fix for this problem, so updating vscode-languageclient will probably fix it.
https://github.com/microsoft/vscode-languageserver-node/commit/b72a5613a101b2a630ce29d709215a47a437b6b5

**Comment by ckilb** [comment]
I just like to mention that this issue still exists.
