### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by innocenzi** [phpactor/vscode-phpactor#37]
Hey,

I'm looking for an intelephense replacement since it's closed-source and the development is slow, and phpactor seems like an excellent candidate. 

I was trying out this extension locally but I couldn't make it work at all. The language server crashes and restart in a loop. 

Here is the complete log:

```
tarting language server, use -vvv for verbose output
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 20480 bytes) in /Users/enzoinnocenzi/Library/Application Support/Code/User/globalStorage/dantleech.vscode-phpactor/phpactor/lib/WorseReflection/Core/SourceCodeLocator/ChainSourceLocator.php on line 55
[Info  - 2:52:52 AM] Connection to server got closed. Server will restart.
[Error - 2:52:52 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 2:52:52 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 2:52:52 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 2:52:52 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 2:52:52 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 2:52:52 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 2:52:52 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 2:52:52 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 2:52:52 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 2:52:52 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 2:52:52 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 2:52:52 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 2:52:52 AM] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/enzoinnocenzi/Code/playground/vscode-phpactor/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
```

Steps to reproduce:
- Follow instruction installation
  - I cloned the extension repository, installed dependencies using yarn, built the project, and symlinked it to the VSC extension directory.
- Start VSCode within a PHP project using Composer (Laravel project in my case)

**Comment by dantleech** [comment]
Hi, does it work in other projects? Does it start indexing? If it starts indexing, do you see the memory usage rise?

Just tried it on a Laravel project in Code and works for me :thinking:

**Comment by innocenzi** [comment]
I have both these messages: 

![image](https://user-images.githubusercontent.com/16060559/179388712-e9cf8a70-56fd-45cc-b22f-c40800b1e6d1.png)

Then a few seconds later I get the server crash.

> Hi, does it work in other projects?

I created an empty PHP project and required `symfony/process`, there was no crash

![image](https://user-images.githubusercontent.com/16060559/179388860-e3c5b495-3195-4e0a-8dc9-1998b09e28e0.png)

**Comment by innocenzi** [comment]
Additionnal note: it does work on a fresh Laravel project. I'll try to find out what's causing the crash in my other Laravel project.

**Comment by dantleech** [comment]
certainy an issue with Phpactor core, i'll move the issue.
